# Generated by Django 5.2.1 on 2025-05-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
