# Generated by Django 5.2.1 on 2025-05-28 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_table_alter_product_table_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
