# Generated by Django 5.2.1 on 2025-05-28 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.CharField(max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_amount',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ord_quantity',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
