# Generated by Django 5.2.1 on 2025-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_contact_account_dob_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_brand',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
