# Generated by Django 5.2.1 on 2025-05-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_prod_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_quantity',
            new_name='prod_stock',
        ),
    ]
