# Generated by Django 5.2.1 on 2025-05-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_prod_quantity_product_prod_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feed_commnet', models.TextField()),
                ('feed_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
