# Generated by Django 5.2.1 on 2025-05-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
